---
- hosts: all
  become: true

  tasks:
  - name: ensure cowsay is installed
    apt:
      name: cowsay
      state: present

  - name: add docker repository
    shell: |
      add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      apt-get update

  - name: add lime user
    user:
        name: lime
        comment: "Lime runner user"
        group: sudo

  - name: install all required packages
    apt:
      name: "{{ item }}"
      state: present
      allow_unauthenticated: yes # for docker-ce
    with_items:
      - rsync
      - python3-pip
      - python3-venv
      - mysql-server
      - libmysqlclient-dev
      - libffi-dev
      - libssl-dev
      - supervisor
      - python3-mysqldb
      - docker-ce
      - virtualenv

  - name: make sure /lime-code exists
    file:
      path: "/lime-code"
      state: directory

  - name: copy code to /lime-code
    synchronize:
      src: "/lime/"
      dest: "/lime-code"

  - name: install virtualenv
    pip:
      name: virtualenv
      virtualenv: "/lime-code/venv"

  - name: install packages in virtualenv
    pip:
      virtualenv: "/lime-code/venv"
      requirements: "/lime-code/lime/requirements.txt"

  - name: Create a new database for lime
    mysql_db:
      name: lime
      state: present

  - name: Copy supervisor file
    copy:
      src: "/lime-code/lime/supervisor/lime.conf"
      dest: "/etc/supervisor/conf.d/lime.conf"
      remote_src: True

  - name: Run migrations
    shell: /lime-code/lime/upgrade.sh

  - name: Restart lime app
    supervisorctl:
      name: lime
      state: restarted
